do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'export_job_status'
      and n.nspname = 'public'
  ) then
    create type public.export_job_status as enum (
      'queued',
      'running',
      'completed',
      'failed',
      'expired',
      'cancelled'
    );
  end if;
end $$;

create table if not exists public.export_job (
  id uuid primary key default gen_random_uuid(),
  requested_by uuid not null references auth.users (id) on delete cascade,
  export_type text not null,
  source_table text not null,
  query_params jsonb not null default '{}'::jsonb,
  filters jsonb not null default '{}'::jsonb,
  sort jsonb not null default '{}'::jsonb,
  column_order text[] not null default '{}'::text[],
  status public.export_job_status not null default 'queued',
  row_count integer,
  file_size_bytes bigint,
  storage_bucket text,
  storage_path text,
  error_message text,
  attempt_count integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.export_job_row (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.export_job (id) on delete cascade,
  row_index integer not null,
  row_data jsonb not null,
  created_at timestamptz not null default now(),
  unique (job_id, row_index)
);

create index if not exists export_job_status_created_at_idx
  on public.export_job (status, created_at);

create index if not exists export_job_requested_by_created_at_idx
  on public.export_job (requested_by, created_at desc);

create index if not exists export_job_expires_at_idx
  on public.export_job (expires_at);

create index if not exists export_job_row_job_id_row_index_idx
  on public.export_job_row (job_id, row_index);

create or replace function public.touch_export_job_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_export_job_updated_set_timestamp on public.export_job;
create trigger on_export_job_updated_set_timestamp
before update on public.export_job
for each row execute function public.touch_export_job_updated_at();

create or replace function public.claim_next_export_job()
returns setof public.export_job
language sql
security definer
set search_path = public
as $$
  with next_job as (
    select id
    from public.export_job
    where status = 'queued'::public.export_job_status
      and (expires_at is null or expires_at > now())
    order by created_at asc
    for update skip locked
    limit 1
  ), claimed as (
    update public.export_job job
    set status = 'running'::public.export_job_status,
        started_at = coalesce(job.started_at, now()),
        attempt_count = job.attempt_count + 1,
        error_message = null,
        updated_at = now()
    where job.id in (select id from next_job)
    returning job.*
  )
  select * from claimed;
$$;

alter table public.export_job enable row level security;
alter table public.export_job_row enable row level security;

create policy export_job_read_own
  on public.export_job
  for select
  using (requested_by = auth.uid());

create policy export_job_read_authorized
  on public.export_job
  for select
  using (public.authorize('profiles.read'));

create policy export_job_insert_own
  on public.export_job
  for insert
  with check (
    requested_by = auth.uid()
    and public.authorize('profiles.read')
  );

create policy export_job_update_own
  on public.export_job
  for update
  using (requested_by = auth.uid() and public.authorize('profiles.read'))
  with check (requested_by = auth.uid() and public.authorize('profiles.read'));

create policy export_job_read_auth_admin
  on public.export_job
  for select
  to supabase_auth_admin
  using (true);

create policy export_job_write_auth_admin
  on public.export_job
  for all
  to supabase_auth_admin
  using (true)
  with check (true);

create policy export_job_row_read_own
  on public.export_job_row
  for select
  using (
    exists (
      select 1
      from public.export_job job
      where job.id = export_job_row.job_id
        and job.requested_by = auth.uid()
    )
  );

create policy export_job_row_insert_own
  on public.export_job_row
  for insert
  with check (
    exists (
      select 1
      from public.export_job job
      where job.id = export_job_row.job_id
        and job.requested_by = auth.uid()
        and public.authorize('profiles.read')
    )
  );

create policy export_job_row_read_auth_admin
  on public.export_job_row
  for select
  to supabase_auth_admin
  using (true);

create policy export_job_row_write_auth_admin
  on public.export_job_row
  for all
  to supabase_auth_admin
  using (true)
  with check (true);

grant usage on type public.export_job_status to authenticated, supabase_auth_admin;

grant all on table public.export_job to supabase_auth_admin;
revoke all on table public.export_job from authenticated, anon, public;
grant select, insert, update on table public.export_job to authenticated;

grant all on table public.export_job_row to supabase_auth_admin;
revoke all on table public.export_job_row from authenticated, anon, public;
grant select, insert on table public.export_job_row to authenticated;

grant execute on function public.claim_next_export_job() to supabase_auth_admin;
