import { type RouteConfig, route, index } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("home", "routes/home.tsx"),
  route("info", "routes/info.tsx"),
  route("forms", "routes/forms.tsx"),
  route("enroll", "routes/enroll.tsx"),
  route("enroll/:semesterId", "routes/enroll.$semesterId.tsx"),
  route("my-forms", "routes/my-forms.tsx"),
  route("my-forms/:formId", "routes/my-forms.$formId.tsx"),
  route("semester-surveys/:semesterId/pre-program", "routes/semester-surveys.pre.tsx"),
  route("semester-surveys/:semesterId/pre", "routes/semester-surveys.pre-redirect.tsx"),
  route("login", "routes/auth/login.tsx"),
  route(
    "sign-up",
    "routes/sign-up/layout.tsx",
    [
      index("routes/sign-up/index.tsx"),
      route("terms", "routes/sign-up/terms.tsx"),
      route("invite", "routes/sign-up/invite.tsx"),
    ]
  ),
  // Two-stage signup details step (must register to avoid 404)
  route("auth/sign-up-details", "routes/auth/sign-up-details.tsx"),
  route("auth/waiting-on-guardian", "routes/auth/waiting-on-guardian.tsx"),
  route("logout", "routes/auth/logout.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("update-password", "routes/auth/update-password.tsx"),
  route("profile", "routes/profile.tsx"),
  route("profile/:profileID", "routes/profile.$id.tsx"),
  route("protected", "routes/protected.tsx"),
  route("auth/confirm", "routes/auth/confirm.tsx"),
  route("auth/error", "routes/auth/error.tsx"),
  route("zlr/:token", "routes/zlr.$token.ts"),
  route("internal/export-jobs/run", "routes/internal/export-jobs.run.ts"),
  route("internal/export-jobs/cleanup", "routes/internal/export-jobs.cleanup.ts"),
  route("internal/zoom-jobs/run", "routes/internal/zoom-jobs.run.ts"),
  route("internal/zoom-jobs/reset", "routes/internal/zoom-jobs.reset.ts"),
  route("manage", "routes/manage/team.tsx", [
    index("routes/manage/index.tsx"),
    route("participants", "routes/manage/participants.tsx"),
    route("person", "routes/manage/person.tsx", [
      index("routes/manage/person.overview.tsx"),
      route("family", "routes/manage/person.family.tsx"),
      route("enrollments", "routes/manage/person.enrollments.tsx"),
      route("form-submissions", "routes/manage/person.form-submissions.tsx"),
      route("activity", "routes/manage/person.activity.tsx"),
      route("attendance", "routes/manage/person.attendance.tsx"),
      route("discrepancies", "routes/manage/person.discrepancies.tsx"),
    ]),
    route("team", "routes/manage/team-members.tsx"),
    route("families", "routes/manage/families.tsx"),
    route("workshop", "routes/manage/workshop.tsx"),
    route("workshop/setup", "routes/manage/workshop.setup.tsx"),
    route("class", "routes/manage/class.tsx"),
    route("class-attendance", "routes/manage/class-attendance.tsx"),
    route("zoom-host", "routes/manage/zoom-host.tsx"),
    route("zoom-connect-test", "routes/manage/zoom-connect-test.tsx"),
    route("class-zoom-meeting", "routes/manage/class-zoom-meeting.tsx"),
    route("class-zoom-registrant", "routes/manage/class-zoom-registrant.tsx"),
    route("class-zoom-participant-sync", "routes/manage/class-zoom-participant-sync.tsx"),
    route("class-zoom-participant", "routes/manage/class-zoom-participant.tsx"),
    route("zlr-click-event", "routes/manage/zlr-click-event.tsx"),
    route("workshop-enrollment", "routes/manage/workshop-enrollment.tsx"),
    route("workshop-enrollment/enrichment", "routes/manage/workshop-enrollment.enrichment.ts"),
    route("form", "routes/manage/form.tsx"),
    route("form/:formID/answers", "routes/manage/form.$id.answers.tsx"),
    route("form/:formID", "routes/manage/form.$id.tsx"),
    route("form-question", "routes/manage/form-question.tsx"),
    route("sign-up-terms/new", "routes/manage/sign-up-terms.new.tsx"),
    route("sign-up-terms/:termId/edit", "routes/manage/sign-up-terms.$termId.edit.tsx"),
    route("sign-up-terms", "routes/manage/sign-up-terms.tsx"),
    route("sign-up-terms-consent", "routes/manage/sign-up-terms-consent.tsx"),
    route("form-question-map", "routes/manage/form-question-map.tsx"),
    route("form-assignment", "routes/manage/form-assignment.tsx"),
    route("form-submission", "routes/manage/form-submission.tsx"),
    route("login-event", "routes/manage/login-event.tsx"),
    route("ip-org-policy", "routes/manage/ip-org-policy.tsx"),
    route("email-message", "routes/manage/email-message.tsx"),
    route("email-drafts", "routes/manage/email-drafts.tsx"),
    route("email-drafts/:draftId", "routes/manage/email-drafts.$draftId.tsx"),
    route("form-answer", "routes/manage/form-answer.tsx"),
    route("gift-cards", "routes/manage/gift-cards.tsx"),
    route("role-permission", "routes/manage/role-permission.tsx"),
    route("user-roles", "routes/manage/user-roles.tsx"),
    route("invites", "routes/manage/invites.tsx"),
    route("discrepancies", "routes/manage/discrepancies.tsx"),
    route("request-metadata", "routes/manage/request-metadata.tsx"),
    route("exports", "routes/manage/exports.tsx"),
    route("exports/:jobId/download", "routes/manage/exports.$jobId.download.ts"),
    route("geoip-backfill", "routes/manage/geoip-backfill.tsx"),
    route("riding-lookup", "routes/manage/riding-lookup.tsx"),
    route("family-context/enrichment", "routes/manage/family-context.enrichment.ts"),
    route("federal-electoral-district/enrichment", "routes/manage/federal-electoral-district.enrichment.ts"),
    route("federal-electoral-district", "routes/manage/federal-electoral-district.tsx"),
    route("semester", "routes/manage/semester.tsx"),
    route("semester-form-requirement", "routes/manage/semester-form-requirement.tsx"),
  ]),
] satisfies RouteConfig;
