export const teamPages = [
  { to: '/manage', label: 'Overview', description: 'Admin workspace and quick links.' },
  { to: '/manage/workshop-enrollment', label: 'Workshop enrollments', description: 'Pending, waitlisted, approved, and rejected workshop enrollments.' },
  { to: '/manage/workshop', label: 'Workshops', description: 'Current workshop sections and limits.' },
  { to: '/manage/class', label: 'Classes', description: 'Individual class schedule entries.' },
  { to: '/manage/class-attendance', label: 'Class attendance', description: 'Attendance by class and student.' },
  { to: '/manage/semester', label: 'Semesters', description: 'Program semesters and enrollment windows.' },
  { to: '/manage/semester-form-requirement', label: 'Semester surveys', description: 'Map one pre/post survey form per semester.' },
  { to: '/manage/participants', label: 'Participants', description: 'Guardians, students, and unassigned users.' },
  { to: '/manage/families', label: 'Families', description: 'Guardian/child relationships.' },
  { to: '/manage/team', label: 'Team', description: 'Instructors and staff roles.' },
  { to: '/manage/gift-cards', label: 'Gift cards', description: 'Upload and process gift card batches.' },
  { to: '/manage/form', label: 'Forms', description: 'Onboarding forms configuration.' },
  { to: '/manage/form-question', label: 'Form questions', description: 'Questions tied to forms.' },
  { to: '/manage/sign-up-terms', label: 'Sign-up terms', description: 'Active terms copy shown during account creation.' },
  { to: '/manage/sign-up-terms-consent', label: 'Terms consent', description: 'Accepted terms snapshots captured at signup.' },
  { to: '/manage/form-question-map', label: 'Form question map', description: 'Questions mapped to forms and ordering.' },
  { to: '/manage/form-assignment', label: 'Form assignments', description: 'Assignments per user.' },
  { to: '/manage/form-submission', label: 'Form submissions', description: 'User response metadata.' },
  { to: '/manage/form-answer', label: 'Form answers', description: 'Individual answers with JSON value.' },
  { to: '/manage/invites', label: 'Invites', description: 'Pending/confirmed invitations.' },
  { to: '/manage/login-event', label: 'Login events', description: 'Successful sign-in metadata and source context.' },
  { to: '/manage/discrepancies', label: 'Discrepancies', description: 'Suspicious signals from address and network inconsistencies.' },
  { to: '/manage/request-metadata', label: 'Request metadata', description: 'Validate proxy headers and extracted request metadata.' },
  { to: '/manage/role-permission', label: 'Role permissions', description: 'Permissions assigned to each role.' },
  { to: '/manage/user-roles', label: 'User roles', description: 'The role each user currently holds.' },
]
