export const teamPages = [
  { to: '/manage', label: 'Overview', description: 'Admin workspace and quick links.' },
  { to: '/manage/workshop-enrollment', label: 'Workshop enrollments', description: 'Pending and approved workshop enrollments.' },
  { to: '/manage/class-attendance', label: 'Class attendance', description: 'Attendance by class and student.' },
  { to: '/manage/workshop', label: 'Workshops', description: 'Current workshop sections and limits.' },
  { to: '/manage/invites', label: 'Invites', description: 'Pending/confirmed invitations.' },
  { to: '/manage/participants', label: 'Participants', description: 'Guardians, students, and unassigned users.' },
  { to: '/manage/team', label: 'Team', description: 'Instructors and staff roles.' },
  { to: '/manage/class', label: 'Classes', description: 'Individual class schedule entries.' },
  { to: '/manage/person-guardian-child', label: 'Guardian child links', description: 'Guardian/child relationships.' },
  { to: '/manage/form', label: 'Forms', description: 'Onboarding forms configuration.' },
  { to: '/manage/form-question', label: 'Form questions', description: 'Questions tied to forms.' },
  { to: '/manage/form-question-map', label: 'Form question map', description: 'Questions mapped to forms and ordering.' },
  { to: '/manage/form-assignment', label: 'Form assignments', description: 'Assignments per user.' },
  { to: '/manage/form-submission', label: 'Form submissions', description: 'User response metadata.' },
  { to: '/manage/form-answer', label: 'Form answers', description: 'Individual answers with JSON value.' },
  { to: '/manage/gift-cards', label: 'Gift cards', description: 'Upload and process gift card batches.' },
  { to: '/manage/role-permission', label: 'Role permissions', description: 'Permissions assigned to each role.' },
  { to: '/manage/user-roles', label: 'User roles', description: 'The role each user currently holds.' },
  { to: '/manage/semester', label: 'Semesters', description: 'Program semesters and enrollment windows.' },
]
