[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["**/*"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
